### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by frankreno**
fix dashboard URL, update README with Mac install steps and add note that MFA must be disabled.

### CODE REVIEW

**Comment by frankreno** [comment]
canceling as PR #2 solves the issue already and adds support SES...

**Comment by kumoroku** [comment]
I am reopening this for now because it is a smaller change than #2 and I want to keep the surface area for testing small until I can reproduce the parameter change actually works (full disclosure: I got tangled up yesterday night on this)

**Comment by frankreno** [comment]
@kumoroku : just noticed an issue, let me correct before you test, not sure how that got in.

**Comment by frankreno** [comment]
good to test now...

**Pull request closed without merging**
